config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  post '/home/fetch_movies' => 'home#fetch_movies'
  get '/home/get_detail/:id/:city_id' => 'home#get_detail'
  get '/home/update_cities' => 'home#update_cities'

  root 'home#index'

end

app/models/cinema.rb
class Cinema < ActiveRecord::Base
	belongs_to :city
	has_many :movies
end

app/models/cinemas_movie.rb
class CinemasMovie < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :cinemas
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	belongs_to :cinemas
	has_many :movietimes
end

app/models/movietime.rb
class Movietime < ActiveRecord::Base
	belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require 'cities'
require 'movies'
class HomeController < ApplicationController
  def index
  	@cities = City.all
  end
  def fetch_movies
  	@movies = Movie.where(:city_web_id => params[:city][:name],:movie_date => params[:date])
  	if @movies.blank?
  		fetch_movies = Movies.fetch(params[:city][:name],params[:date])	
  		if fetch_movies
  			@movies = Movie.where(:city_web_id => params[:city][:name],:movie_date => params[:date])
  		end
  	end
  	@city = City.where(:city_web_id => params[:city][:name]).last
  	@date = params[:date]
  end
  def get_detail
  	@movie = Movie.where(:movie_web_id => params[:id]).last
  	city = City.where(:city_web_id => params[:city_id]).last
  	@cinemas = city.cinemas
  	if @movie.movietimes.blank?
  		fetch_movie_detail = Movies.fetch_detail(params[:city_id],params[:id])	
  	end
  end
  def update_cities
  	cities = City.all
  	if cities.present?
	  	cities.destroy_all
	  end	
  	Cities.fetch
  	redirect_to request.referer, :notice => "Successfully Updated!"
  end
end
	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/fetch_movies.html.erb
<% if @movies.present? %>
<h1><%= @city.name %></h1>
<h2><%= @date %></h2>
<ul>
	<% @movies.each do |movie| %>
		<li>
			<%=movie.name%><br>
			<a href="/home/get_detail/<%=movie.movie_web_id%>/<%=movie.city_web_id%>">Get Detail</a>
			<br>
		</li>
	<% end %>
</ul>
<% else %>
<strong>No Movies at this date!</strong>
<% end %>
<%= link_to "back", home_index_path %>

app/views/home/get_detail.html.erb
<%= @cinema.inspect %>
<%=@movie.movietimes.inspect%>

app/views/home/index.html.erb
<a href="/home/update_cities">Update Cities Data</a><br>
<% today = Date.today 
	@days_from_this_week = (today.at_beginning_of_week..today.at_end_of_week).map
%>
<%= form_tag(home_fetch_movies_path, method: "post") do %>
	<%= select(:city, :name, City.all.collect {|b| [b.name, b.city_web_id]}) %>
	<%= select_tag :date, options_for_select(@days_from_this_week) %>	
	<%= submit_tag "Get Movies" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Showtimes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>